### ISSUE TITLE
Setup - Issue

### ISSUE THREAD

**Issue by ghost** [BrandonE/lichocker#16]
Hey ho. I tried to set up this docker image and i've ran into this error below. Could you give a hint how i could solve that issue?

Error:
27:C 04 Jan 19:54:40.786 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
27:C 04 Jan 19:54:40.786 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=27, just started
27:C 04 Jan 19:54:40.786 # Configuration loaded
nohup: appending output to 'nohup.out'
about to fork child process, waiting until server is ready for connections.
forked process: 52
child process started successfully, parent exiting
: invalid option
/bin/sh: 0: Illegal option -

**Comment by greg-finley** [comment]
It looks like you successfully run up to here: https://github.com/BrandonE/lichocker/blob/master/run.sh#L10

Could you check the output in `nohup.out` in `lila-ws`? It should end with `INFO l.w.n.NettyServer [run-main-0] Listening to 9664`

So maybe something with `mongodb`? You can go to `/var/log` and look for either `mongod.log` or something like `mongod.log.2020-01-04T22-45-23`.

I'm surprised it's saying `/bin/sh` because the `run.sh` script is `/bin/bash`. Can you tell me which shell you're using? https://askubuntu.com/a/590902

**Comment by greg-finley** [comment]
Also, please share your `docker run` command if you want.

**Comment by ghost** [comment]
Sorry for the late response. I checked for the nohup.out:
```
copying runtime jar...
copying runtime jar...
copying runtime jar...
copying runtime jar...
[info] [launcher] getting org.scala-sbt sbt 1.3.6  (this may take some time)...
copying runtime jar...
copying runtime jar...
[info] [launcher] getting org.scala-sbt sbt 1.3.6  (this may take some time)...
```
Also I tried to look into the /var/log but couldn't get inside the container because after the error above it exits with: `lishogi_lichess_1 exited with code 2`

After that I tried to build the image from the dockerfile, to avoid running run.sh at the beginning and get into the container, but it doesn't get finished:
`sudo: unable to execute /home/lichess/build/node-init.sh: No such file or directory`

I assume it is because I try to run it on windows(Docker Desktop for Windows) but I can't see why it should affect the shell used inside the container.

My docker run command:
'docker run --volume C:\Path\to\dir\lila:/home/lichess/projects/lila --volume C:\Path\to\dir\lila-ws:/home/lichess/projects/lila-ws --publish 9663:9663 --publish 9664:9664 --name lichess randone211/lichess'

**Comment by Bugouser** [comment]
> : invalid option
> /bin/sh: 0: Illegal option -

Had same issue trying install chocker from windows.
You have to change end of line symbol in sh scripts from windows (CRLF) to unix (LF). Use notepad++ or similar tools

**Comment by greg-finley** [comment]
@Bugouser good catch! Do you mind filing a PR? It would be great if we could get the image building and running both working for Windows.

**Comment by greg-finley** [comment]
Do you feel CRLF is in the git repo? I looked at Dockerfile and `run.sh` on my cloned version and I don't think they have CRLF.

**Comment by Bugouser** [comment]
> Do you feel CRLF is in the git repo? I looked at Dockerfile and `run.sh` on my cloned version and I don't think they have CRLF.

Seems it depends on git client settings. On windows default line ending crlf, while on linux lf.
[Git docs](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings)
[Stackowerflow](https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf)
[Similar problem](https://github.com/carlossg/docker-maven/issues/114)

So, before git clone on Windows, i think, we need to do:
`git config --global core.autocrlf input` <--better solution
or manually replace crlf in script files or may be other files

**Comment by ghost** [comment]
So i tried to change the file endings in sh files. Unfortunately it wasn't enough. But with `git config --global core.autocrlf input` before pulling also lila and lila-ws it finally works. Thanks guys.
