### ISSUE TITLE
Error: ./run.sh: 21: ./run.sh: ./bin/dev: not found ./run.sh: 24: ./run.sh: ./bin/dev: not found

### ISSUE THREAD

**Issue by Dyex719** [BrandonE/lichocker#2]
Hello! I am having a few issues in getting the container to run.
I cloned lila from https://github.com/ornicar/lila and stored it in  ~/Documents/lichess/lila

However in the step, 
`sudo docker run     --volume ~/Documents/lichess/lila:/home/lichess/projects/lila     --publish 80:80     --publish 9663:9663     --name lichess     --interactive     --tty     brandone211/lichess`

I get the error
`Error: ./run.sh: 21: ./run.sh: ./bin/dev: not found ./run.sh: 24: ./run.sh: ./bin/dev: not found`.

Any help would be appreciated!

**Comment by Dyex719** [comment]
Sorry.  I didn't clone lila into the lichocker directory.

**Comment by raquelhortab** [comment]
Hi! I am experiencing the same problem. What I did was add the clone commands to the dockerfile so lila would be directly cloned to /home/lichess/projects/lila. All works fine until I get
```
./run.sh: 22: ./run.sh: ./bin/dev: not found
./run.sh: 25: ./run.sh: ./bin/dev: not found
```

What did you mean by cloning into the lickhocker directory? Isn't it enough to have the lila project inside /home/lichess/projects/ ? 

Thanks!

**Comment by raquelhortab** [comment]
solved! forgot to run some commands ( `cp lila/bin/dev.default lila/bin/dev && chmod +x lila/bin/dev` , etc)
