### ISSUE TITLE
CSS not displaying?

### ISSUE THREAD

**Issue by ipkpjersi** [BrandonE/lichocker#6]
Hi,

I am able to get the docker container running, scala compiles the files and then the Netty HTTP server seems to run as I can access localhost:9663 but the CSS appears to not be loading: 
![2018-12-2_23-52-18_1543812738956147773](https://user-images.githubusercontent.com/33754783/49353768-8232f780-f68d-11e8-8703-332775742ad3.png)

Here is the command I use to run docker:
`sudo docker run --volume ~/lichess/lichocker/lila:/home/lichess/projects/lila --publish 81:80 --publish 9663:9663 --name lichesslocal --interactive --tty brandone211/lichess`

Here is what the terminal looks like: 
![2018-12-2_23-55-43_1543812943024628637](https://user-images.githubusercontent.com/33754783/49353827-d63ddc00-f68d-11e8-981b-3c15f3cbde34.png)

Any ideas what I might be doing wrong?

Thanks.

**Comment by BrandonE** [comment]
@ipkpjersi,

I believe the issue is that you're binding port 81 on your container to port 80 on your host machine. The nginx server that serves Lichess's assets is listening on port 80. Please try the following instead:

`sudo docker run --volume ~/lichess/lichocker/lila:/home/lichess/projects/lila --publish 80:80 --publish 9663:9663 --name lichesslocal --interactive --tty brandone211/lichess`

Also, it is usually not necessary to use `sudo` when running docker commands. If you need it, consider the following from the docs:

```
To avoid having to use sudo with the docker command, your system administrator can create a Unix group called docker and add users to it. For more information about this configuration, refer to the Docker installation documentation for your operating system.
```

**Comment by ipkpjersi** [comment]
Hi,

As I am a web developer, I already have port 80 in use on my Linux host, so I need to bind to port 81 or another port.

I looked up docker run's syntax here: https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose and according to that page, the syntax is guest:host - or am I mistaken and it is actually host:guest?

Thanks for the quick response.

**Comment by BrandonE** [comment]
You're right, I misread the syntax. Can you temporarily disable your other service on port 80 and confirm that you have the same issue even when running on port 80? If you do not, you may need to modify a setting [here](https://github.com/ornicar/lila/blob/master/conf/base.conf) to indicate that the UI should serve assets from port 81. I haven't looked into this before.

**Comment by ipkpjersi** [comment]
Hi,

I'm not sure it's a port issue as I am getting the same issue now with port 80 - when I go to 127.0.0.1/assets, nginx 1.10.3 reports 403 Forbidden and when I go to http://lichess-assets.local/assets/_VTIIx4/stylesheets/board.css I get 404 Not Found.

I did notice that `http://lichess-assets.local/assets/font82/fonts/lichess.woff` exists and I am able to download that font just fine.

Do you have any ideas?

edit: I copied everything inside of `lila/public` to `lila/public/_VTIIx4` but since this folder name changes on restart it's not a good permanent workaround. Also, when I play a game with the machine, it gets stuck on waiting for opponent: ![](https://i.imgur.com/HQSp30O.png)

Thanks.

**Comment by BrandonE** [comment]
Nothing immediately comes to mind regarding your first issue. I haven't heard of ever needing to copy the public directory.

To answer your question about playing with the computer, you have to follow [this optional step](https://github.com/BrandonE/lichocker/blob/master/README.md#optional-setup-fishnet-for-server-side-analysis-and-play) or else the computer will never make any moves.

**Comment by ipkpjersi** [comment]
For fishnet, is that something that can be used offline for local-only play or is that something that requires an Internet connection?

**Comment by BrandonE** [comment]
@ipkpjersi Sorry for the delayed response. You can use fishnet to play Stockfish locally, yes.

Are you still experiencing the issues described above?

**Comment by ipkpjersi** [comment]
Hi,

I never did end up solving it so I deleted what I had thus far, but for offline local-only play I just ended up grabbing the Android APK mobile file which works great offline which is all I was really interested in - I wasn't super available to develop anyways. So, I'd say for all purposes, this can now be closed since I don't have time to troubleshoot these days. If someone else runs into this issue and has time to troubleshoot it, you can of course feel free to re-open this.

Cheers.

**Comment by ipkstef** [comment]
I'm currently having this issue, was there any headway with resolving this? 
Docker run commands: 
docker run \
    --volume /home/xxxx/lila:/home/lichess/projects/lila \
    --publish 80:80 \
    --publish 9663:9663 \
    --name lichess \
    --interactive \
    --tty \
    brandone211/lichess
![image](https://user-images.githubusercontent.com/34087181/54471555-509ff100-4791-11e9-8fe7-c4d0c2b25703.png)
