### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by arimourao** [BrandonE/lichocker#7]
Hello there,

I followed and revised every step in the docs and when I finally execute the docker run command I get the following:

![screenshot from 2019-02-22 13-00-01](https://user-images.githubusercontent.com/7979806/53254372-fe901200-36a1-11e9-971d-765919d3a271.png)

I'm a bit lost, could you guys give a hand here? Tnx

**Comment by BrandonE** [comment]
Hello,

It appears that [svg-optimize was removed on August 24th, 2018](https://github.com/ornicar/lila/commits/master/bin/svg-optimize). The [Lichess Development Onboarding](https://github.com/ornicar/lila/wiki/Lichess-Development-Onboarding) steps were updated accordingly:

![image](https://user-images.githubusercontent.com/542245/53674209-f875d480-3c51-11e9-909e-af416f656320.png)

It looks like we should delete the ` && ./bin/svg-optimize` [here](https://github.com/BrandonE/lichocker/blob/master/run.sh#L18) to remove that error message, though this shouldn't be a fatal error. I just merged a PR that fixes this issue. Thanks @Nicals !

Regarding the other errors, can you confirm that you ran this command from the prerequisites? `cp lila/bin/dev.default lila/bin/dev && chmod +x lila/bin/dev`

**Comment by arimourao** [comment]
Yes I'm pretty sure I ran this command.

**Comment by BrandonE** [comment]
I just cloned lichocker and lila to computer that I've never configured for Lichess before. I was able to run lichocker using the steps provided. Here is my `history`:

```
git clone git@github.com:BrandonE/lichocker.git
git clone --recursive https://github.com/ornicar/lila.git
cp lila/bin/dev.default lila/bin/dev && chmod +x lila/bin/dev
cp lila/conf/application.conf.default lila/conf/application.conf
vi /etc/hosts
sudo vi /etc/hosts
docker build --tag brandone211/lichess .
ls
cd lichocker
docker build --tag brandone211/lichess .
docker run \\n    --volume ~/Repo/lila:/home/lichess/projects/lila \\n    --publish 80:80 \\n    --publish 9663:9663 \\n    --name lichess \\n    --interactive \\n    --tty \\n    brandone211/lichess
```

Can you provide your `docker run` command? Make sure to update `~/YOUR/PATH/TO/lila` to point to your cloned lila repository.

**Comment by BrandonE** [comment]
Closing for now. Please re-open if the issue persists.
