### ISSUE TITLE
I'm currently having issues with css

### ISSUE THREAD

**Issue by ipkstef** [BrandonE/lichocker#8]
I'm currently having this issue, was there any headway with resolving this? 
Docker run commands: 
docker run \
    --volume /home/xxxx/lila:/home/lichess/projects/lila \
    --publish 80:80 \
    --publish 9663:9663 \
    --name lichess \
    --interactive \
    --tty \
    brandone211/lichess
![image](https://user-images.githubusercontent.com/34087181/54471555-509ff100-4791-11e9-8fe7-c4d0c2b25703.png)

_Originally posted by @ipkstef in https://github.com/BrandonE/lichocker/issues/6#issuecomment-473504079_

**Comment by BrandonE** [comment]
@greg-finley-ck and I made a major update to Lichocker that appears to fix all of the issues we've been experiencing recently with the old version. Please try the latest Docker image on Docker Hub and re-open this if you have the same issue.
