### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by raquelhortab** [BrandonE/lichocker#9]
Hi there! 
In chrome, whever I try to start a game it gives `Cross origin request forbidden`

In firefox I can start a game but I keep getting the following error in the browser's console:

```
The connection to ws://localhost/RL5k0YmR/white/socket/v4?sri=83f1yq1rnr&v=0 was interrupted while the page was loading. socket.js:61:11
Firefox can't establish a connection to the server at ws://localhost/RL5k0YmR/white/socket/v4?sri=83f1yq1rnr&v=0. socket.js:61:11
[round 83f1yq1rnr] Disconnect socket.js:202:6
[round 83f1yq1rnr] connection attempt to ws://localhost/RL5k0YmR/white/socket/v4?sri=83f1yq1rnr&v=0
```

Thanks for everything!

**Comment by BrandonE** [comment]
@greg-finley-ck and I made a major update to Lichocker that appears to fix all of the issues we've been experiencing recently with the old version. Please try the latest Docker image on Docker Hub and re-open this if you have the same issue.
